### ISSUE TITLE
画像アップロードの際に画像以外のファイルを添付できてしまう

### ISSUE THREAD

**Issue by m-yamashita** [lodge/lodge#100]
DnDで画像以外のファイルをアップロードすると、普通に成功してしまう。

この時imgタグによりリンク切れ画像のような表示のされ方をするが、ファイルの実体は正常にアップロードされており、画像のURLをコピーする等で直接URLを叩くことダウンロードできてしまう。

仕様として画像以外のアップロードに対応するか、画像以外を禁止にするなどの対策が必要。

**Comment by m-yamashita** [comment]
個人的にはファイルを許可してしまうとナレッジとしてサイト内で完結できず、開かなければ分からないようなOffice系ファイルで溢れかえる事が想定されるため簡単には許可したくないと思っています。

**Comment by kakusuke** [comment]
そうですね、Office系ファイルは弾きたいですね
画像のみ許容するようにしたほうが良さそうです
