### ISSUE TITLE
フォローしていないタグの最新記事と、最新タグの一覧を右メニューに表示

### ISSUE THREAD

**Issue by m-yamashita** [lodge/lodge#111]
現状運用として下記の点が問題になってるのではないかと感じます。
- 新しいトピック(タグ)について何か投稿しても誰にも気づいて貰えない。
- タグ一覧を能動的に見に行かないと新しいタグが出来たことに気づけない
- トップページがフォローしてるタグの投稿しかでない
- 人気記事一覧はあるものの、ポピュラーなタグ以外は読まれないのでそもそも人気記事にすらならない。

これらの解決策として、表題の様な機能が必要と考えます。

わりと早急に解決したい問題なので、次回リリースまでに何とかしたいと思います。

**Comment by kakusuke** [comment]
あまり右側のメニュー増やすのはゴチャゴチャして見にくくなるし1ペインあたりの表示件数が減ってかえって気づきにくくなるのでは？
投稿記事一覧を外して
新着記事一覧の件数を増やすなどはいかがでしょう

**Comment by m-yamashita** [comment]
投稿記事一覧は結構使うのですが、新着記事の方が優先度は高いように感じますね。あと新着タグの一覧はやはり欲しいなと思います。タグ一覧はおそらく最も見に行かないページだと思うので。五件とかで良いし、二週間以内に追加されたものだけ表示とかでいいとは思いますが…。

いっそのこと、トップページをfeedじゃなくarticlesにしてしまうのも効果的かもしれません。

**Comment by kakusuke** [comment]
現在、右のペインにはいろんな性質の情報が混在しているので、例えば新規性の高いものだけに限定して表示する場所にしたほうが良いと思います

具体的にはメニューと投稿記事をヘッダーに押しこめ、新規タグ一覧、新規記事一覧を表示するだけに留めるのが良いのではないでしょうか
ストックした記事に関してはすぐに検索できればよいかと思います

無関係なプロジェクトに対する記事も大量に出てくると思われる新着記事一覧より、
属人性を含んだ一覧を表示するfeedのほうが、トップページにはふさわしいと思います
そこは変更しないほうがよいかと

**Comment by m-yamashita** [comment]
#131 にて対応済みです。 リリースされ次第本IssueはCloseします。

**Comment by m-yamashita** [comment]
v0.10.3 によりリリースしました。よってCloseします。
