### ISSUE TITLE
不正なコードブロック記法で記事を開く時にエラーになる

### ISSUE THREAD

**Issue by shiena** [lodge/lodge#123]
developブランチで以下のようにインラインとコードブロックを間違えた時に記事を保存できるのですが、開く時にエラーになってしまいます。`a`の部分は他の文字でも同様です。
/articles/xxx/editのようなURLを直接入力して編集画面を開けるので復旧は可能です。

``````
```a```
b
``````

以下は記事を開いたときのエラーログです。

``````
I, [2014-10-28T15:43:01.248745 #6687]  INFO -- : Completed 500 Internal Server Error in 28ms
F, [2014-10-28T15:43:01.251683 #6687] FATAL -- : 
ActionView::Template::Error (Invalid id given: a```):
    42: 
    43:   <div class="panel-body markdown">
    44:     <%= @article.body_toc.html_safe %>
    45:     <%= @article.body_html.html_safe %>
    46:   </div>
    47: </div>
    48: 
  app/models/concerns/markdownable.rb:26:in `block in markdown'
  app/models/concerns/markdownable.rb:23:in `markdown'
  app/models/concerns/markdownable.rb:8:in `block (2 levels) in markdownable'
  app/views/articles/show.html.erb:45:in `_app_views_articles_show_html_erb___2773584092377693264_70014297834520'
  config/initializers/quiet_assets.rb:6:in `call_with_quiet_assets'
``````

また、試行錯誤で分かったのですが以下の1行ではエラーは起きずに記事を開く事ができました。

``````
```a```
``````

**Comment by m-yamashita** [comment]
ご報告ありがとうございます。
現象を確認しました。
Markdownパーサを入れ替える事を現在検討しているため、しばらくお待ちいただければと思います。

ご不便をお掛けしますが、よろしくお願いいたします。

**Comment by shiena** [comment]
ご確認ありがとうございます。
復旧手段がありますので気長に待っています。

**Comment by shiena** [comment]
v0.10.1で報告したパターンのエラーが解消されました。
ご対応ありがとうございます。

ですが、今度は以下のようにスペース4つのコードブロックに```のコードブロックを書くと一番上のパターンだけ表示が崩れるようになってしまいました。

``````
## ファイル種別とファイル名を記述

    ```foo:bar
    baz
    ```

## ファイル種別のみ記述

    ```foo
    baz
    ```

## ファイル種別もファイル名も記述なし

    ```
    baz
    ```
``````

![codeblock](https://cloud.githubusercontent.com/assets/1295639/5083309/f096705e-6f36-11e4-95c8-f050ecac015a.PNG)

**Comment by m-yamashita** [comment]
ご報告ありがとうございます。
まだMarkdownパーサの入れ替えは完了していないため、 ~~v0.11.0までお待ちいただく形となってしまいます。~~ 次期バージョンにて実装予定です。 ご不便をおかけしますが、宜しくお願いします。

**Comment by m-yamashita** [comment]
#143 にて対応しました。

以下の様に表示されるようになります。期待通りかと思われますので、本件は次回のリリース後にCloseしたいと思います。

![issue01](https://cloud.githubusercontent.com/assets/4678722/7468211/5dc46cc0-f340-11e4-9e08-d965fdd60218.png)
![issue02](https://cloud.githubusercontent.com/assets/4678722/7468215/64d56fd2-f340-11e4-872f-ef814124919d.png)

**Comment by m-yamashita** [comment]
リリース完了しましたのでCloseします。

**Comment by shiena** [comment]
修正ありがとうございます。
不正なコードブロックでもエラーが起きなくなりました。
