### ISSUE TITLE
サンプルサイトのアカウントがいくつか凍結状態にあるようです

### ISSUE THREAD

**Issue by tanabata-kitajima** [lodge/lodge#169]
サンプルサイトで、ログインしての利用を試みてみました。その結果、
以下のアカウント
user01@example.com
user02@example.com
user04@example.com
user05@example.com
について、「あなたのアカウントはロックされています。」と表示されログインできませんでした。

何らかの対処をお願いできますでしょうか？

**Comment by m-yamashita** [comment]
すみません、メンテナンスの都合上、Herokuのサンプルサイトについては一旦閉鎖し、Gifアニメによるイメージ等に差し替えるつもりです。
ご報告ありがとうございました。

**Comment by m-yamashita** [comment]
サンプルサイトは記載から消したのでCloseさせていただきます。
