### ISSUE TITLE
ドラッグ＆ドロップ以外で画像を添付することはできますか？

### ISSUE THREAD

**Issue by t-adachi** [lodge/lodge#170]
またまた失礼致します。
画像の添付がドラッグ＆ドロップで出来、大変便利なのですが
画像の添付をするためのボタンを付けるといったことは可能でしょうか？

Javascriptを見る限りだと、fileInputのonChangeに対応してそうに見えたのですが・・・。

**Comment by m-yamashita** [comment]
現状DnD以外からのファイルアップロードは実装しておらず、特に不便もないことから実装予定も今のところはございません。申し訳ありませんが、ご了承ください。
