### ISSUE TITLE
NoMethodError: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by yokochi** [lodge/lodge#171]
以下でエラーが発生しました
irb(main):007:0> Article.first.comments.size
NoMethodError: undefined method `name' for nil:NilClass
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/associations/has_many_association.rb:79:in`cached_counter_attribute_name'
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/associations/has_many_association.rb:75:in `has_cached_counter?'
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/associations/has_many_association.rb:60:in`count_records'
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/associations/collection_association.rb:294:in `size'
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/associations/collection_proxy.rb:729:in`size'
    from (irb):7
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/console.rb:90:in `start'
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/console.rb:9:in`start'
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:69:in `console'
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in`run_command!'
    from /opt/lodge/vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands.rb:17:in `<top (required)>'

railsのversion変更で回避しました
-gem 'rails', '4.1'
+gem 'rails', '4.1.14'

4.1.0のバグでしょうか
https://github.com/activescaffold/active_scaffold/issues/380

**Comment by m-yamashita** [comment]
ご報告ありがとうございます。
一先ずはバージョン固定で対応したいと思います。

**Comment by m-yamashita** [comment]
#172 にて対応済み、Releaseの為Close
