### ISSUE TITLE
ruby2.1だとqiita-markdownをインストールできない

### ISSUE THREAD

**Issue by cappyzawa** [lodge/lodge#189]
READMEに
> Ruby 2.1, 2.2, 2.3

と記載されていましたが2.1だとqiita-markdownの依存関係を解決できませんでした

2.2にバージョンアップすると無事に解決できました。

**Comment by m-yamashita** [comment]
ご報告ありがとうございます。
環境が古くなってきているので、近々Rubyバージョンのサポート情報も更新しようと思います。
