### ISSUE TITLE
記事を編集日時ではなく作成日時順で並べるよう修正する。

### ISSUE THREAD

**Issue by m-yamashita** [lodge/lodge#21]
そもそも編集された記事を上に持ってくるのは、通知機能がなかった時代に実装した暫定仕様だった為もはや必要無いと考えられる為、ちゃんと作成日時順を維持するよう修正する。

**Comment by nacika-ins** [comment]
かなり良いプロジェクトだと思います！もし暇があったらプルリク送りますー。

**Comment by m-yamashita** [comment]
ありがとうございますっ！僕一人ではほとんど週末と通勤電車でしか開発できないのでご協力いただけると幸いです＞＜；

**Comment by m-yamashita** [comment]
public_editブランチにてついでに実装してしまいました。

**Comment by m-yamashita** [comment]
マージしました https://github.com/m-yamashita/lodge/commit/877770eb7f8429f1818102399d654ccf7f0929d4
