### ISSUE TITLE
コードブロックの表示方法

### ISSUE THREAD

**Issue by m-yamashita** [lodge/lodge#25]
# 現状

現状では横サイズ制限、自動改行はせず、はみ出たらスクロールバー。
ちなみにQiitaではプレビューで確認する限りだと自動改行になるようだ。
縦サイズは無制限。

上記のような形で実装しているが、
大きなコードブロックになると非常に見難い。

縦も横も大きなコードだった場合、
最下部にしかスクロールバーが出ないため一般のユーザーは一度最下部にいってスクロールしなければならずかなりストレスがたまる。
# 対策

そこで、以下のような仕様にするのはどうか。
- 縦幅はmaxを画面内に収まる程度に固定。それ以上は縦スクロールバー表示
- 横幅はこれまで通り、自動改行もしない。
## 何が解決するか

縦幅が固定されることにより常に横スクロールバーに安定してアクセスができるようになる。このサイズはpx固定にするか、jsによりブラウザサイズから計算させるかは要検討。

他に良い案があれば教えてください。

**Comment by comuttun** [comment]
対策ではないのですが、コードブロックに関連するのでここに要望を書かせていただきます。

## コードブロックのコピーに対する改善希望

コードブロックをコピーすると、行番号もコピーされてしまいますので、以下のような修正がされるとうれしいです
- 行番号がコピーされないようにする (GitHub などはこっちですね）
- 行番号を表示しないようにする (Qiita はこれですね）
- raw リンクを用意して、ハイライトしない版を開けるようにする

ご検討よろしくお願いいたします

**Comment by m-yamashita** [comment]
ご要望ありがとうございます！

あれ、おかしいな…行番号はコピーされないはずと認識しています（あまり細かく確認できていませんが少なくともChromeでは）。

行番号と本文の境目に線などがないので、分かり難いということなのかもしれません。
試しに行頭ではなく本文中腹あたりからドラッグしてみたらいけませんか？

境目が分かり難い為に選択しづらいという問題であれば、その通りだと思いますのでなにかしら対策したいと思います。

もし本当に行番号も含めて選択されてしまう状況が回避できないのであれば、環境を教えていただけないでしょうか？宜しくお願いします。

**Comment by comuttun** [comment]
> 行番号と本文の境目に線などがないので、分かり難いということなのかもしれません。
> 試しに行頭ではなく本文中腹あたりからドラッグしてみたらいけませんか？

大変失礼しました。堺目より前をドラッグしていて、行番号が選択されていました＞＜

> 境目が分かり難い為に選択しづらいという問題であれば、その通りだと思いますのでなにかしら対策したいと思います。

背景色が変わっているか線が入ってるかされていると良いなと感じます。

**Comment by m-yamashita** [comment]
おお！よかったです！(｡>﹏<｡)

そうですね、罫線を入れるのを考えてましたが、色という手もありましたね…！検討してみます！ありがとうございました！

**Comment by m-yamashita** [comment]
ひとまずはQiita方式(縦幅無制限、横幅画面に合わせ、自動改行)にしました。 #108
