### ISSUE TITLE
developブランチを作成しました。

### ISSUE THREAD

**Issue by m-yamashita** [lodge/lodge#27]
開発版はこちらに。masterは今後安定版としてタグを打つタイミングでのみマージします。
今後のPullRequestはdevelopブランチにお願いいたします。

**Comment by kakusuke** [comment]
develop -> master
master -> release

とでもしたほうが、無用な混乱を避けるという意味でよいのではないでしょうか

**Comment by kakusuke** [comment]
#37

**Comment by comuttun** [comment]
master ブランチを削除して、 develop ブランチをデフォルトにする手もあるかと思います
（デフォルトブランチはリポジトリ設定画面で変えられます）

**Comment by m-yamashita** [comment]
そうですね、やはり分かりづらいでしょうか。
一般的なやり方はどうなのかと思って他の大手リポジトリをいくつか参考にしたりしてこうしてみたのですが･･･。

普通にユーザがプロジェクト上のURLからコピーしてCloneしてくるとmasterになってしまうので、
そのまま不安定版を使われてバグが上がってくるのを恐れていました。

なのでこの場合は、やはりエンドユーザ向けにはREAMEで案内して、
releaseページから、zipでダウンロードしてもらうといった形にする方がいいですかね？
自分もWikiやIssueを見てもらうより、releaseブランチを切ってあげたほうがPR時の間違いは起きない気はしています・・・。

**Comment by comuttun** [comment]
master 無し (develop, release, etc構成）でいかがでしょうか？
設定画面からデフォルトブランチを切り替えると、 `git push origin :master` で消せるようになります

**Comment by kakusuke** [comment]
その場合、clone した時はどのブランチが落ちてきて、PR の時のデフォルトはどうなるかわかりますか？

**Comment by comuttun** [comment]
clone はデフォルトブランチが落ちてきます。PRのデフォルトは明確には覚えてませんが、デフォルトブランチになるはずです。

**Comment by kakusuke** [comment]
なるほど。だとすると、間違ったPRを防ぐという意味ではあまり嬉しくないですね・・・

インストール手順 で 最新の安定版を clone するように記載しておくのが無難な気がします

**Comment by comuttun** [comment]
お？私の想定では、
- develop -> デフォルト
- release -> リリース、タグ打ち用
- 他 -> 作業ブランチ

となるつもりでした。

ですので、PRも develop にくるという状態です。
これだと何か困りますでしょうか？

**Comment by m-yamashita** [comment]
使いたいだけの一般ユーザがdevelopを間違ってcloneしてしまう可能性がある点ですね。
なので、上記の @kakusuke さんの方法と組み合わせると嬉しい感じかもしれません。

`git clone -b` でブランチ指定ができるそうなので、READMEにそっちを持っていく感じでどうでしょうか？

**Comment by kakusuke** [comment]
:+1: 

`git clone -b` ではタグも指定できるので、`release`ブランチはいらないかもしれませんね

**Comment by comuttun** [comment]
使いたいだけの方には、 [Releases](https://github.com/m-yamashita/lodge/releases) から tarball を落としてね、とREADMEに書いて上げるのが親切な気もします。 git を使うことができる人にはある程度わかる説明が書いてあれば十分ではないでしょうか(^^;

**Comment by kakusuke** [comment]
:+1: 
これなら git 使えない人にも使ってもらえますし、こっちのほうがいいですね

**Comment by m-yamashita** [comment]
自分も最初そう思って書いてから気づいたんですが、上記からtar及びzipでインストールする方法だと、
恐らくアップデートやデータ移行が非常にめんどくさい事になりそうな予感が・・・。

アップデート手順としてREADMEに、`git pull`して`bundle install`して`rake db:migrate`すればOK!というわけにはいかなくなるんじゃないかなぁと思います。（ディレクトリ上書きは怖いですし

**Comment by comuttun** [comment]
（将来的には）RubyGems で gem update lodge のようにできるのがいいんじゃないかと(^^;

**Comment by m-yamashita** [comment]
それすごいｗ

では当面の間、READMEには「アップデート予定のある方はgitを使ってreleaseブランチからcloneしてね、そうじゃない人はreleaseページからzip及びtarballをダウンロードできるよ」という扱いでどうでしょうかね？

アップデートのためにpullすることを考えると、やはりreleaseブランチ自体は残しておくという感じにしてはいかがでしょうか？

**Comment by comuttun** [comment]
:thumbsup:

**Comment by kakusuke** [comment]
盲点でした
:+1:

**Comment by m-yamashita** [comment]
では以下の構成で作成します。
- release
- develop(default)
- etc...

READMEには、「gitを使ったupdatableなインストール」と「git要らずでとりあえずインストール」の2種類を併記。

こんな感じでいこうと思います。皆さんありがとうございました。

**Comment by m-yamashita** [comment]
ブランチの変更は終わりました、ご確認ください。

**Comment by m-yamashita** [comment]
思ったんですがデフォルトブランチ変えると最初にこのGitHub開いた人が目にするREADMEはdevelopのものになりますね・・・。

ということは、変更すべきREADME.mdはdevelop側になると思いますが、そのREADMEは既にreleaseとインストール方法が異なるという・・・。

**Comment by m-yamashita** [comment]
嫌な予感がしたので、とりあえずdefaultブランチだけはreleaseに向け先を戻しておきました。
ひとまずエンドユーザにはこのままで害は出ないと思います。。。

**Comment by comuttun** [comment]
確かにそうですね。
README への記載は最小限にして、Wiki に追い出すのがシンプルではないでしょうか？

もしくは、 README.md はリリース版同等にして、 DEVELOPMENT.md のようなものを用意するほうがいいかもしれません。

[こんな感じで](https://github.com/adam-p/markdown-here/blob/master/NOTES.md) レンダリングはきちんとしてくれますので、README.md にリンクとして用意するので良いかなと。

**Comment by kakusuke** [comment]
僕もユーザー向けと開発者向けは完全に分けたほうがいいと思います

もうちょっと大きくなったら[GitHub pages](https://pages.github.com/)でユーザー向けのアナウンスをしてもいいかもしれませんね
今はちょっと余裕ないと思いますが・・・

**Comment by m-yamashita** [comment]
確かにファイルを分けるのがいいかもしれません。
README.mdには、補足的に「developer向け」みたいな感じで「DEVELOP.md」を参照するよう促す一文を入れておく感じでどうでしょうか？

あともうひとつ根本的な事なのですが、こんな感じで色々と問題が出るのであれば、
やはりdevelopをデフォルトブランチにしてしまうのをやめてしまうという手もあるかと思います。
一般的に開発向けブランチがデフォルトになっているケースというのはあまりないように感じていますし、PRする方が間違えないようになっていればいい気もします。

これまでは「master」というありきたりな名前だったので迷いが生まれていたような気もしますが、
「release」というブランチに名称を変更したことで、
いきなりこんな名前のブランチにPRを送るようなことは考えにくいかなぁという気がしています。

もちろんその上で、Wiki上に開発者はdevelopにPRして頂く旨の記載はする。それがあれば十分じゃないかなぁと思うのですが、やはり開発ブランチをdefaultにした方が良いでしょうか？

**Comment by m-yamashita** [comment]
もしそれで同じようなPRがあった際はその旨を伝えてPRしなおしてもらうだけで解決するんじゃないかなーと思いました。

**Comment by m-yamashita** [comment]
デフォルトは今まで通りreleaseになったので、このIssueはCloseします。
