### ISSUE TITLE
ヘッダーナビゲーションの再考

### ISSUE THREAD

**Issue by kakusuke** [lodge/lodge#28]
現状では記事の新規作成リンクが記事一覧が表示されている画面からでないと表示されないようです
記事の作成はメインの機能だと思うので、どこからでもアクセスできるようにヘッダーに設置したほうがよいのではないでしょうか
また、現在「編集」という文言のリンクがヘッダーにありますが、何に対する編集なのかわかりにくいように感じました

そういったことも含めて、再度考えなおすのがよいと思います

**Comment by m-yamashita** [comment]
これは実際に運用している現場からも何人かから同じ意見を頂いており、
改善すべきポイントだと思っていましたので、ご指摘の通りだと思います！

是非考え直しましょう。

まず新規作成ですが、本家Qiitaのようにレフトメニューの一番上に大きめのイメージリンクとして設置しておくのがわかりやすいかもしれません。大きければそれだけ「作成しなきゃ！」という気にもなるような気がしますしｗ

ヘッダ部にある「編集」リンクに関しては、「アカウント設定」のような名称に変更し、自身のユーザだった場合のみ、例のユーザ情報ポップアップ内の右上あたりにリンクを入れてしまうのがわかりやすいかなと思いました。

文言さえ変わっていれば迷うことはないとは思うので、あのままの位置においてあげても問題ないかもしれませんが、そうそう使う機能でもないので、ユーザポップアップ内に入れてしまうのもありかと思います。

よくある他様のサイトを真似るなら、ポップアップ式メニューリストにして、
ログアウトと並べるのもいいかもしれません。

**Comment by kakusuke** [comment]
そうですね、「編集」は文言を変えてポップアップ内で良いと思います
個人的には「ログアウト」もボタンか何かにしてポップアップ内に押し込めてもいいんじゃないかと考えてます
基本ログアウトしないですよね？

あと、「◯ Contributions」もポップアップ内にありますし、取ってしまってもいいんじゃないでしょうか？
その代わり、おっしゃるようにでかでかと記事投稿アイコンを置くのはわかりやすいと思います

こうするとヘッダーが1行でおさまるようになり、薄い感じになります
それが嫌なのであれば、検索バーをヘッダー内右側下辺りにもってくるのがよいでしょうか

配置のイメージとしては

| ロ | ゴ |  | 新規投稿 | 通知件数 | プロフィール |
| --- | --- | --- | --- | --- | --- |
| ロ | ゴ |  |  |  | 検索バー |

のような感じです

**Comment by m-yamashita** [comment]
自身のContributionは常に表示される位置にあった方が、増えたとき嬉しいしやる気も出るという現場からの強い要望があったためあの位置に配置していました。実際あそこにあると結構気にするようになって、楽しさは増したように思えましたので、常に表示することにはそれなりに意味があるように思えます。

ただ、無理にヘッダー内にねじ込んでおく必要性はないと思うので、配置については考える余地があるかと思っています。

新規投稿アイコンはレフトメニュー内を想定してましたので、ヘッダには埋め込まなくても良いと思います。そうすればヘッダはもっとダイエットできますしシンプルでよいかなと。

ログアウトの位置については…。確かにログアウトって基本しないのですが、ユーザー情報表示用のポッアップ内にあるのは違和感がありますね…よそ様のサイト見ると大体右上についてて、隠してある場合は代わりに右上に歯車的アイコンがあってクリックによりリストが出てくるといった感じでしょうか。

スペースを取りたくないなら歯車導入しても良いかもしれませんね。それがあればアカウント編集もそこに入れておけますし、実装するかわかりませんが、テーマ切り替えのような個人設定なんかの画面に遷移するのも可能になると思いますし。

ロゴ     ユーザ名 歯車

な感じでかなりスッキリできそうな気がします。どうでしょうか？

**Comment by m-yamashita** [comment]
あ、通知件数の位置は今まで通りなので、この場合ですと歯車とユーザ名の間になりますかね。

ロゴのみ左寄せなイメージです。

**Comment by kakusuke** [comment]
なるほど、「レフトメニュー」をヘッダー右上の部分だと勝手に勘違いして話をしていました
メインコンテンツの右のペインのことですね

ロゴ ユーザ名 通知件数 歯車

だいぶスッキリですね！いいんじゃないでしょうか

Contributionがあそこに配置してあるのはそういう意図だったんですね
個人的には新規投稿アイコンと一緒に右ペインに入れるのが、ヘッダーを軽く出来ていいと思います

あと検索バーですが、記事全体に関する検索機能のほかに、例えば自分のストックした記事の検索機能を実装すると思うんです
GitHubのように開いてるページの文脈で検索かけるようにしますか？
それともグローバルな検索バー以外に、各ページごとに検索バーを配置しますか？

後者であれば、今の配置ですとおそらく検索バーが縦に2つ並ぶようになってしまい、ちょっと見苦しくなるかなーと感じました

**Comment by m-yamashita** [comment]
Contribution右ペインは僕も概ね賛成です。ただあそこに入れるのにどういう表現をするかがちょっと難しいと感じていてそこが悩みどころです。あれ一つのためにレフトメニューの見出しが一つ増えるのは微妙ですよね…。

検索バーについてはちょっと考えてあって、色んな用途で検索をかけると思うしその度にAPIもUIも拡張していかなきゃならないことを考えると、シンプルに検索タイプを指定するようなセレクトボックスをつけるのはどうでしょう？

```
[タグ名で  ][Java            ] [検索]
[タイトルで][Java            ] [検索]
[ユーザーで][m-yamashita     ] [検索]
```

一つ目のブロックがセレクトボックス、二つ目がテキスト、三つ目が検索ボタンなイメージです。

たとえばこの構成に、さらに「どこから」かを指定するセレクトボックスがもう一つ並べばかなり柔軟な思い通りの挙動が実現できそうな気がします。

それによるControllerもしくはModelの実装も大変になりそうですが…！

**Comment by m-yamashita** [comment]
本件ほぼ対応済みです。

検索バーについては全文検索とクエリ方式を採用しましたので、1つのボックスでいろいろ検索できる形になりました。
#165 で対応、リリース予定です。

**Comment by m-yamashita** [comment]
Releaseの為Closeします。
