### ISSUE TITLE
Markdown上に画像を埋め込んだ際に非常に小さく表示されてしまう。

### ISSUE THREAD

**Issue by m-yamashita** [lodge/lodge#33]
CSSでwidth, heightともに20に固定されてしまっているのが原因、早めに直したい。

**Comment by kakusuke** [comment]
#20 では直ってます

**Comment by m-yamashita** [comment]
なんとなくそんな気はしてました！ありがとうございます！

**Comment by m-yamashita** [comment]
https://github.com/lodge/lodge/commit/d9f55a22e0add145588f27d1e0e0a59bcbec8146 にてdevelopにマージ、 https://github.com/lodge/lodge/commit/6e2d894e683d06b14fae6e8ae90b425ee883de04 にて最大幅の調整を行いましたので、本件Closeします。
