### ISSUE TITLE
メール送信設定をもう少し柔軟にしたい

### ISSUE THREAD

**Issue by comuttun** [lodge/lodge#39]
#35 の修正中に気づいたのですが、現在の `.env` を使う方法は、
- development
  - ~~config.action_mailer.delivery_method = :sendmail~~
  - 追記: 勘違いです、こちらも :smtp 固定ですね
- production
  - `config.action_mailer.delivery_method = :smtp`

に固定されていて、方法を選ぶことができません。

社内構築の場合ですと外部SMTPに繋ぐ方が稀な気がしますので、
.env に delivery_method も追い出してしまい、設定値を development / production 両方とも同じように反映されるようにしたほうが良さそうです。

**Comment by m-yamashita** [comment]
確かに仰るとおりかと思います。PR頂ければマージしたいと思います、ありがとうございます！
