### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by comuttun** [lodge/lodge#45]
GitHub と連携できる [Gitter](https://gitter.im) というのがあります。（[参考記事](http://maoe.hatenadiary.jp/entry/2014/01/17/GitHub%E3%81%A8%E9%80%A3%E6%90%BA%E3%81%99%E3%82%8B%E3%83%81%E3%83%A3%E3%83%83%E3%83%88%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9Gitter%E3%81%8C%E4%BE%BF%E5%88%A9%E3%81%9D%E3%81%86)）

Issue にたてるまでもないような相談事をしたりする場所があってもいいのかなあという気が少ししましたので、良ければご検討ください。

参考までに、私のフォークしたリポジトリのチャットを貼っておきます （誰でも参加できます）
https://gitter.im/comutt/lodge

**Comment by m-yamashita** [comment]
公式なやつ作りました、よろしくお願いします！
[![Gitter chat](https://badges.gitter.im/m-yamashita/lodge.png)](https://gitter.im/m-yamashita/lodge)

Issueだけじゃなくて要望とかも気軽にかけそうでいい感じですね！

**Comment by comuttun** [comment]
ありがとうございます！ :thumbsup:
