### ISSUE TITLE
TravisCIでconfig/environmentsの設定がなされていない

### ISSUE THREAD

**Issue by yasuhiroki** [lodge/lodge#48]
#47 でTravisCIのビルドに失敗している原因。

**Comment by kakusuke** [comment]
https://github.com/kakusuke/lodge/commit/251d37a56ed3d40588a578a367d242e5e02e7c6b にて解決しました

**Comment by yasuhiroki** [comment]
ありがとうございます。
.envを使うんでしたね...。すみません。
