### ISSUE TITLE
Markdownヘルプ表示が消えない&重複表示される

### ISSUE THREAD

**Issue by m-yamashita** [lodge/lodge#95]
#93 のマージ後に見つけたバグです。

記事の新規投稿及び編集では問題ありませんでしたが、コメント部にも同様のヘルプ表示用のトリガーがあり、これをクリックしヘルプ表示後、任意の箇所をクリックし閉じようとすると暗転部分のみ残り続けてしまい操作不能となります。

また既にコメントが追加された状態で、コメント部の編集をクリックしエリアを表示させ、そこをクリックするとポップアップが二重に開いてしまいます。

GoogleChromeで確認しました。

**Comment by zenizh** [comment]
確認します。
ありがとうございます！

**Comment by zenizh** [comment]
1. まず、コメント部分については、私の方がコメント部もlayouts/_editor.html.erbを使っていることに気づいていないことが問題でした。
2. 二重ポップアップについても、layouts/_editor.html.erbにモーダルのHTMLを書いていて、コメントの数だけモーダルのHTMLが出力されることが問題でした。

2点とも修正のメドはつきましたので、改めてプルリク送ります！

**Comment by m-yamashita** [comment]
ご確認ありがとうございます！お待ちしていますー。
